/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as AuthVerifyOtpIndexRouteImport } from './routes/auth/verify-otp/index'
import { Route as AuthProfileIndexRouteImport } from './routes/auth/profile/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as ProtectedProjectSlugIndexRouteImport } from './routes/_protected/project/$slug/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const AuthVerifyOtpIndexRoute = AuthVerifyOtpIndexRouteImport.update({
  id: '/verify-otp/',
  path: '/verify-otp/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthProfileIndexRoute = AuthProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ProtectedProjectSlugIndexRoute =
  ProtectedProjectSlugIndexRouteImport.update({
    id: '/project/$slug/',
    path: '/project/$slug/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/profile/': typeof AuthProfileIndexRoute
  '/auth/verify-otp/': typeof AuthVerifyOtpIndexRoute
  '/project/$slug/': typeof ProtectedProjectSlugIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/': typeof ProtectedIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/profile': typeof AuthProfileIndexRoute
  '/auth/verify-otp': typeof AuthVerifyOtpIndexRoute
  '/project/$slug': typeof ProtectedProjectSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/_protected/': typeof ProtectedIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/profile/': typeof AuthProfileIndexRoute
  '/auth/verify-otp/': typeof AuthVerifyOtpIndexRoute
  '/_protected/project/$slug/': typeof ProtectedProjectSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth/login/'
    | '/auth/profile/'
    | '/auth/verify-otp/'
    | '/project/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/auth/login'
    | '/auth/profile'
    | '/auth/verify-otp'
    | '/project/$slug'
  id:
    | '__root__'
    | '/_protected'
    | '/auth'
    | '/_protected/'
    | '/auth/login/'
    | '/auth/profile/'
    | '/auth/verify-otp/'
    | '/_protected/project/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/auth/verify-otp/': {
      id: '/auth/verify-otp/'
      path: '/verify-otp'
      fullPath: '/auth/verify-otp/'
      preLoaderRoute: typeof AuthVerifyOtpIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/profile/': {
      id: '/auth/profile/'
      path: '/profile'
      fullPath: '/auth/profile/'
      preLoaderRoute: typeof AuthProfileIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_protected/project/$slug/': {
      id: '/_protected/project/$slug/'
      path: '/project/$slug'
      fullPath: '/project/$slug/'
      preLoaderRoute: typeof ProtectedProjectSlugIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedProjectSlugIndexRoute: typeof ProtectedProjectSlugIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedProjectSlugIndexRoute: ProtectedProjectSlugIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthProfileIndexRoute: typeof AuthProfileIndexRoute
  AuthVerifyOtpIndexRoute: typeof AuthVerifyOtpIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthProfileIndexRoute: AuthProfileIndexRoute,
  AuthVerifyOtpIndexRoute: AuthVerifyOtpIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
