/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVerifyOtpIndexRouteImport } from './routes/auth/verify-otp/index'
import { Route as AuthProfileIndexRouteImport } from './routes/auth/profile/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyOtpIndexRoute = AuthVerifyOtpIndexRouteImport.update({
  id: '/verify-otp/',
  path: '/verify-otp/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthProfileIndexRoute = AuthProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/profile/': typeof AuthProfileIndexRoute
  '/auth/verify-otp/': typeof AuthVerifyOtpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/profile': typeof AuthProfileIndexRoute
  '/auth/verify-otp': typeof AuthVerifyOtpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/profile/': typeof AuthProfileIndexRoute
  '/auth/verify-otp/': typeof AuthVerifyOtpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth/login/'
    | '/auth/profile/'
    | '/auth/verify-otp/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/auth/login' | '/auth/profile' | '/auth/verify-otp'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/auth/login/'
    | '/auth/profile/'
    | '/auth/verify-otp/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-otp/': {
      id: '/auth/verify-otp/'
      path: '/verify-otp'
      fullPath: '/auth/verify-otp/'
      preLoaderRoute: typeof AuthVerifyOtpIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/profile/': {
      id: '/auth/profile/'
      path: '/profile'
      fullPath: '/auth/profile/'
      preLoaderRoute: typeof AuthProfileIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthProfileIndexRoute: typeof AuthProfileIndexRoute
  AuthVerifyOtpIndexRoute: typeof AuthVerifyOtpIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthProfileIndexRoute: AuthProfileIndexRoute,
  AuthVerifyOtpIndexRoute: AuthVerifyOtpIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
