// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.4
// source: proto/project.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "project";

export enum ProjectVisibility {
  PROJECT_VISIBILITY_UNSPECIFIED = 0,
  PROJECT_VISIBILITY_PUBLIC = 1,
  PROJECT_VISIBILITY_PRIVATE = 2,
  UNRECOGNIZED = -1,
}

export function projectVisibilityFromJSON(object: any): ProjectVisibility {
  switch (object) {
    case 0:
    case "PROJECT_VISIBILITY_UNSPECIFIED":
      return ProjectVisibility.PROJECT_VISIBILITY_UNSPECIFIED;
    case 1:
    case "PROJECT_VISIBILITY_PUBLIC":
      return ProjectVisibility.PROJECT_VISIBILITY_PUBLIC;
    case 2:
    case "PROJECT_VISIBILITY_PRIVATE":
      return ProjectVisibility.PROJECT_VISIBILITY_PRIVATE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ProjectVisibility.UNRECOGNIZED;
  }
}

export function projectVisibilityToJSON(object: ProjectVisibility): string {
  switch (object) {
    case ProjectVisibility.PROJECT_VISIBILITY_UNSPECIFIED:
      return "PROJECT_VISIBILITY_UNSPECIFIED";
    case ProjectVisibility.PROJECT_VISIBILITY_PUBLIC:
      return "PROJECT_VISIBILITY_PUBLIC";
    case ProjectVisibility.PROJECT_VISIBILITY_PRIVATE:
      return "PROJECT_VISIBILITY_PRIVATE";
    case ProjectVisibility.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum ProjectStatus {
  PROJECT_STATUS_UNSPECIFIED = 0,
  PROJECT_STATUS_CREATED = 1,
  PROJECT_STATUS_RUNNING = 2,
  PROJECT_STATUS_PAUSED = 3,
  PROJECT_STATUS_RESTARTING = 4,
  PROJECT_STATUS_ERROR = 5,
  PROJECT_STATUS_REMOVING = 6,
  PROJECT_STATUS_EXITED = 7,
  PROJECT_STATUS_DEAD = 8,
  UNRECOGNIZED = -1,
}

export function projectStatusFromJSON(object: any): ProjectStatus {
  switch (object) {
    case 0:
    case "PROJECT_STATUS_UNSPECIFIED":
      return ProjectStatus.PROJECT_STATUS_UNSPECIFIED;
    case 1:
    case "PROJECT_STATUS_CREATED":
      return ProjectStatus.PROJECT_STATUS_CREATED;
    case 2:
    case "PROJECT_STATUS_RUNNING":
      return ProjectStatus.PROJECT_STATUS_RUNNING;
    case 3:
    case "PROJECT_STATUS_PAUSED":
      return ProjectStatus.PROJECT_STATUS_PAUSED;
    case 4:
    case "PROJECT_STATUS_RESTARTING":
      return ProjectStatus.PROJECT_STATUS_RESTARTING;
    case 5:
    case "PROJECT_STATUS_ERROR":
      return ProjectStatus.PROJECT_STATUS_ERROR;
    case 6:
    case "PROJECT_STATUS_REMOVING":
      return ProjectStatus.PROJECT_STATUS_REMOVING;
    case 7:
    case "PROJECT_STATUS_EXITED":
      return ProjectStatus.PROJECT_STATUS_EXITED;
    case 8:
    case "PROJECT_STATUS_DEAD":
      return ProjectStatus.PROJECT_STATUS_DEAD;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ProjectStatus.UNRECOGNIZED;
  }
}

export function projectStatusToJSON(object: ProjectStatus): string {
  switch (object) {
    case ProjectStatus.PROJECT_STATUS_UNSPECIFIED:
      return "PROJECT_STATUS_UNSPECIFIED";
    case ProjectStatus.PROJECT_STATUS_CREATED:
      return "PROJECT_STATUS_CREATED";
    case ProjectStatus.PROJECT_STATUS_RUNNING:
      return "PROJECT_STATUS_RUNNING";
    case ProjectStatus.PROJECT_STATUS_PAUSED:
      return "PROJECT_STATUS_PAUSED";
    case ProjectStatus.PROJECT_STATUS_RESTARTING:
      return "PROJECT_STATUS_RESTARTING";
    case ProjectStatus.PROJECT_STATUS_ERROR:
      return "PROJECT_STATUS_ERROR";
    case ProjectStatus.PROJECT_STATUS_REMOVING:
      return "PROJECT_STATUS_REMOVING";
    case ProjectStatus.PROJECT_STATUS_EXITED:
      return "PROJECT_STATUS_EXITED";
    case ProjectStatus.PROJECT_STATUS_DEAD:
      return "PROJECT_STATUS_DEAD";
    case ProjectStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface CreateProjectRequest {
  slug: string;
  userId: string;
  templateId: string;
  description?: string | null | undefined;
  visibility: ProjectVisibility;
}

export interface CreateProjectResponse {
  project: Project | null;
}

export interface GetProjectRequest {
  slug: string;
  userId: string;
}

export interface GetProjectResponse {
  project: Project | null;
}

export interface StartProjectRequest {
  slug: string;
  userId: string;
}

export interface StartProjectResponse {
}

export interface GetAllProjectsRequest {
  userId: string;
}

export interface GetAllProjectsResponse {
  projects: Project[];
}

export interface EditProjectRequest {
  slug: string;
  userId: string;
  description?: string | null | undefined;
  visibility?: ProjectVisibility | null | undefined;
  templateId?: string | null | undefined;
  fileSystemPath?: string | null | undefined;
  status?: ProjectStatus | null | undefined;
  containerUrl?: string | null | undefined;
}

export interface EditProjectResponse {
  project: Project | null;
}

export interface Project {
  id: string;
  slug: string;
  description?: string | null | undefined;
  visibility: ProjectVisibility;
  fileSystemPath: string;
  status: ProjectStatus;
  templateId: string;
  userId: string;
  containerUrl?: string | null | undefined;
  createdAt: string;
  updatedAt: string;
}

function createBaseCreateProjectRequest(): CreateProjectRequest {
  return { slug: "", userId: "", templateId: "", description: null, visibility: 0 };
}

export const CreateProjectRequest: MessageFns<CreateProjectRequest> = {
  encode(message: CreateProjectRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.slug !== "") {
      writer.uint32(10).string(message.slug);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    if (message.templateId !== "") {
      writer.uint32(26).string(message.templateId);
    }
    if (message.description !== undefined && message.description !== null) {
      writer.uint32(34).string(message.description);
    }
    if (message.visibility !== 0) {
      writer.uint32(40).int32(message.visibility);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateProjectRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateProjectRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.slug = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.templateId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.visibility = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateProjectRequest {
    return {
      slug: isSet(object.slug) ? globalThis.String(object.slug) : "",
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      templateId: isSet(object.templateId)
        ? globalThis.String(object.templateId)
        : isSet(object.template_id)
        ? globalThis.String(object.template_id)
        : "",
      description: isSet(object.description) ? globalThis.String(object.description) : null,
      visibility: isSet(object.visibility) ? projectVisibilityFromJSON(object.visibility) : 0,
    };
  },

  toJSON(message: CreateProjectRequest): unknown {
    const obj: any = {};
    if (message.slug !== "") {
      obj.slug = message.slug;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.templateId !== "") {
      obj.templateId = message.templateId;
    }
    if (message.description !== undefined && message.description !== null) {
      obj.description = message.description;
    }
    if (message.visibility !== 0) {
      obj.visibility = projectVisibilityToJSON(message.visibility);
    }
    return obj;
  },

  create(base?: DeepPartial<CreateProjectRequest>): CreateProjectRequest {
    return CreateProjectRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreateProjectRequest>): CreateProjectRequest {
    const message = createBaseCreateProjectRequest();
    message.slug = object.slug ?? "";
    message.userId = object.userId ?? "";
    message.templateId = object.templateId ?? "";
    message.description = object.description ?? undefined;
    message.visibility = object.visibility ?? 0;
    return message;
  },
};

function createBaseCreateProjectResponse(): CreateProjectResponse {
  return { project: null };
}

export const CreateProjectResponse: MessageFns<CreateProjectResponse> = {
  encode(message: CreateProjectResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.project !== undefined && message.project !== null) {
      Project.encode(message.project, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateProjectResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateProjectResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.project = Project.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateProjectResponse {
    return { project: isSet(object.project) ? Project.fromJSON(object.project) : null };
  },

  toJSON(message: CreateProjectResponse): unknown {
    const obj: any = {};
    if (message.project !== undefined && message.project !== null) {
      obj.project = Project.toJSON(message.project);
    }
    return obj;
  },

  create(base?: DeepPartial<CreateProjectResponse>): CreateProjectResponse {
    return CreateProjectResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreateProjectResponse>): CreateProjectResponse {
    const message = createBaseCreateProjectResponse();
    message.project = (object.project !== undefined && object.project !== null)
      ? Project.fromPartial(object.project)
      : null;
    return message;
  },
};

function createBaseGetProjectRequest(): GetProjectRequest {
  return { slug: "", userId: "" };
}

export const GetProjectRequest: MessageFns<GetProjectRequest> = {
  encode(message: GetProjectRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.slug !== "") {
      writer.uint32(10).string(message.slug);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetProjectRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetProjectRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.slug = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetProjectRequest {
    return {
      slug: isSet(object.slug) ? globalThis.String(object.slug) : "",
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
    };
  },

  toJSON(message: GetProjectRequest): unknown {
    const obj: any = {};
    if (message.slug !== "") {
      obj.slug = message.slug;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    return obj;
  },

  create(base?: DeepPartial<GetProjectRequest>): GetProjectRequest {
    return GetProjectRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetProjectRequest>): GetProjectRequest {
    const message = createBaseGetProjectRequest();
    message.slug = object.slug ?? "";
    message.userId = object.userId ?? "";
    return message;
  },
};

function createBaseGetProjectResponse(): GetProjectResponse {
  return { project: null };
}

export const GetProjectResponse: MessageFns<GetProjectResponse> = {
  encode(message: GetProjectResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.project !== undefined && message.project !== null) {
      Project.encode(message.project, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetProjectResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetProjectResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.project = Project.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetProjectResponse {
    return { project: isSet(object.project) ? Project.fromJSON(object.project) : null };
  },

  toJSON(message: GetProjectResponse): unknown {
    const obj: any = {};
    if (message.project !== undefined && message.project !== null) {
      obj.project = Project.toJSON(message.project);
    }
    return obj;
  },

  create(base?: DeepPartial<GetProjectResponse>): GetProjectResponse {
    return GetProjectResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetProjectResponse>): GetProjectResponse {
    const message = createBaseGetProjectResponse();
    message.project = (object.project !== undefined && object.project !== null)
      ? Project.fromPartial(object.project)
      : null;
    return message;
  },
};

function createBaseStartProjectRequest(): StartProjectRequest {
  return { slug: "", userId: "" };
}

export const StartProjectRequest: MessageFns<StartProjectRequest> = {
  encode(message: StartProjectRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.slug !== "") {
      writer.uint32(10).string(message.slug);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StartProjectRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStartProjectRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.slug = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StartProjectRequest {
    return {
      slug: isSet(object.slug) ? globalThis.String(object.slug) : "",
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
    };
  },

  toJSON(message: StartProjectRequest): unknown {
    const obj: any = {};
    if (message.slug !== "") {
      obj.slug = message.slug;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    return obj;
  },

  create(base?: DeepPartial<StartProjectRequest>): StartProjectRequest {
    return StartProjectRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<StartProjectRequest>): StartProjectRequest {
    const message = createBaseStartProjectRequest();
    message.slug = object.slug ?? "";
    message.userId = object.userId ?? "";
    return message;
  },
};

function createBaseStartProjectResponse(): StartProjectResponse {
  return {};
}

export const StartProjectResponse: MessageFns<StartProjectResponse> = {
  encode(_: StartProjectResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StartProjectResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStartProjectResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): StartProjectResponse {
    return {};
  },

  toJSON(_: StartProjectResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<StartProjectResponse>): StartProjectResponse {
    return StartProjectResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<StartProjectResponse>): StartProjectResponse {
    const message = createBaseStartProjectResponse();
    return message;
  },
};

function createBaseGetAllProjectsRequest(): GetAllProjectsRequest {
  return { userId: "" };
}

export const GetAllProjectsRequest: MessageFns<GetAllProjectsRequest> = {
  encode(message: GetAllProjectsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetAllProjectsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAllProjectsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetAllProjectsRequest {
    return {
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
    };
  },

  toJSON(message: GetAllProjectsRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    return obj;
  },

  create(base?: DeepPartial<GetAllProjectsRequest>): GetAllProjectsRequest {
    return GetAllProjectsRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetAllProjectsRequest>): GetAllProjectsRequest {
    const message = createBaseGetAllProjectsRequest();
    message.userId = object.userId ?? "";
    return message;
  },
};

function createBaseGetAllProjectsResponse(): GetAllProjectsResponse {
  return { projects: [] };
}

export const GetAllProjectsResponse: MessageFns<GetAllProjectsResponse> = {
  encode(message: GetAllProjectsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.projects) {
      Project.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetAllProjectsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAllProjectsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.projects.push(Project.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetAllProjectsResponse {
    return {
      projects: globalThis.Array.isArray(object?.projects) ? object.projects.map((e: any) => Project.fromJSON(e)) : [],
    };
  },

  toJSON(message: GetAllProjectsResponse): unknown {
    const obj: any = {};
    if (message.projects?.length) {
      obj.projects = message.projects.map((e) => Project.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<GetAllProjectsResponse>): GetAllProjectsResponse {
    return GetAllProjectsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetAllProjectsResponse>): GetAllProjectsResponse {
    const message = createBaseGetAllProjectsResponse();
    message.projects = object.projects?.map((e) => Project.fromPartial(e)) || [];
    return message;
  },
};

function createBaseEditProjectRequest(): EditProjectRequest {
  return {
    slug: "",
    userId: "",
    description: null,
    visibility: null,
    templateId: null,
    fileSystemPath: null,
    status: null,
    containerUrl: null,
  };
}

export const EditProjectRequest: MessageFns<EditProjectRequest> = {
  encode(message: EditProjectRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.slug !== "") {
      writer.uint32(10).string(message.slug);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    if (message.description !== undefined && message.description !== null) {
      writer.uint32(26).string(message.description);
    }
    if (message.visibility !== undefined && message.visibility !== null) {
      writer.uint32(32).int32(message.visibility);
    }
    if (message.templateId !== undefined && message.templateId !== null) {
      writer.uint32(42).string(message.templateId);
    }
    if (message.fileSystemPath !== undefined && message.fileSystemPath !== null) {
      writer.uint32(50).string(message.fileSystemPath);
    }
    if (message.status !== undefined && message.status !== null) {
      writer.uint32(56).int32(message.status);
    }
    if (message.containerUrl !== undefined && message.containerUrl !== null) {
      writer.uint32(66).string(message.containerUrl);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EditProjectRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEditProjectRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.slug = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.visibility = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.templateId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.fileSystemPath = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.containerUrl = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EditProjectRequest {
    return {
      slug: isSet(object.slug) ? globalThis.String(object.slug) : "",
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      description: isSet(object.description) ? globalThis.String(object.description) : null,
      visibility: isSet(object.visibility) ? projectVisibilityFromJSON(object.visibility) : null,
      templateId: isSet(object.templateId)
        ? globalThis.String(object.templateId)
        : isSet(object.template_id)
        ? globalThis.String(object.template_id)
        : null,
      fileSystemPath: isSet(object.fileSystemPath)
        ? globalThis.String(object.fileSystemPath)
        : isSet(object.file_system_path)
        ? globalThis.String(object.file_system_path)
        : null,
      status: isSet(object.status) ? projectStatusFromJSON(object.status) : null,
      containerUrl: isSet(object.containerUrl)
        ? globalThis.String(object.containerUrl)
        : isSet(object.container_url)
        ? globalThis.String(object.container_url)
        : null,
    };
  },

  toJSON(message: EditProjectRequest): unknown {
    const obj: any = {};
    if (message.slug !== "") {
      obj.slug = message.slug;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.description !== undefined && message.description !== null) {
      obj.description = message.description;
    }
    if (message.visibility !== undefined && message.visibility !== null) {
      obj.visibility = projectVisibilityToJSON(message.visibility);
    }
    if (message.templateId !== undefined && message.templateId !== null) {
      obj.templateId = message.templateId;
    }
    if (message.fileSystemPath !== undefined && message.fileSystemPath !== null) {
      obj.fileSystemPath = message.fileSystemPath;
    }
    if (message.status !== undefined && message.status !== null) {
      obj.status = projectStatusToJSON(message.status);
    }
    if (message.containerUrl !== undefined && message.containerUrl !== null) {
      obj.containerUrl = message.containerUrl;
    }
    return obj;
  },

  create(base?: DeepPartial<EditProjectRequest>): EditProjectRequest {
    return EditProjectRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EditProjectRequest>): EditProjectRequest {
    const message = createBaseEditProjectRequest();
    message.slug = object.slug ?? "";
    message.userId = object.userId ?? "";
    message.description = object.description ?? undefined;
    message.visibility = object.visibility ?? undefined;
    message.templateId = object.templateId ?? undefined;
    message.fileSystemPath = object.fileSystemPath ?? undefined;
    message.status = object.status ?? undefined;
    message.containerUrl = object.containerUrl ?? undefined;
    return message;
  },
};

function createBaseEditProjectResponse(): EditProjectResponse {
  return { project: null };
}

export const EditProjectResponse: MessageFns<EditProjectResponse> = {
  encode(message: EditProjectResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.project !== undefined && message.project !== null) {
      Project.encode(message.project, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EditProjectResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEditProjectResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.project = Project.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EditProjectResponse {
    return { project: isSet(object.project) ? Project.fromJSON(object.project) : null };
  },

  toJSON(message: EditProjectResponse): unknown {
    const obj: any = {};
    if (message.project !== undefined && message.project !== null) {
      obj.project = Project.toJSON(message.project);
    }
    return obj;
  },

  create(base?: DeepPartial<EditProjectResponse>): EditProjectResponse {
    return EditProjectResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EditProjectResponse>): EditProjectResponse {
    const message = createBaseEditProjectResponse();
    message.project = (object.project !== undefined && object.project !== null)
      ? Project.fromPartial(object.project)
      : null;
    return message;
  },
};

function createBaseProject(): Project {
  return {
    id: "",
    slug: "",
    description: null,
    visibility: 0,
    fileSystemPath: "",
    status: 0,
    templateId: "",
    userId: "",
    containerUrl: null,
    createdAt: "",
    updatedAt: "",
  };
}

export const Project: MessageFns<Project> = {
  encode(message: Project, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.slug !== "") {
      writer.uint32(18).string(message.slug);
    }
    if (message.description !== undefined && message.description !== null) {
      writer.uint32(26).string(message.description);
    }
    if (message.visibility !== 0) {
      writer.uint32(32).int32(message.visibility);
    }
    if (message.fileSystemPath !== "") {
      writer.uint32(42).string(message.fileSystemPath);
    }
    if (message.status !== 0) {
      writer.uint32(48).int32(message.status);
    }
    if (message.templateId !== "") {
      writer.uint32(58).string(message.templateId);
    }
    if (message.userId !== "") {
      writer.uint32(66).string(message.userId);
    }
    if (message.containerUrl !== undefined && message.containerUrl !== null) {
      writer.uint32(74).string(message.containerUrl);
    }
    if (message.createdAt !== "") {
      writer.uint32(82).string(message.createdAt);
    }
    if (message.updatedAt !== "") {
      writer.uint32(90).string(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Project {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProject();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.slug = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.visibility = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.fileSystemPath = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.templateId = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.containerUrl = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.updatedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Project {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      slug: isSet(object.slug) ? globalThis.String(object.slug) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : null,
      visibility: isSet(object.visibility) ? projectVisibilityFromJSON(object.visibility) : 0,
      fileSystemPath: isSet(object.fileSystemPath)
        ? globalThis.String(object.fileSystemPath)
        : isSet(object.file_system_path)
        ? globalThis.String(object.file_system_path)
        : "",
      status: isSet(object.status) ? projectStatusFromJSON(object.status) : 0,
      templateId: isSet(object.templateId)
        ? globalThis.String(object.templateId)
        : isSet(object.template_id)
        ? globalThis.String(object.template_id)
        : "",
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      containerUrl: isSet(object.containerUrl)
        ? globalThis.String(object.containerUrl)
        : isSet(object.container_url)
        ? globalThis.String(object.container_url)
        : null,
      createdAt: isSet(object.createdAt)
        ? globalThis.String(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.String(object.created_at)
        : "",
      updatedAt: isSet(object.updatedAt)
        ? globalThis.String(object.updatedAt)
        : isSet(object.updated_at)
        ? globalThis.String(object.updated_at)
        : "",
    };
  },

  toJSON(message: Project): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.slug !== "") {
      obj.slug = message.slug;
    }
    if (message.description !== undefined && message.description !== null) {
      obj.description = message.description;
    }
    if (message.visibility !== 0) {
      obj.visibility = projectVisibilityToJSON(message.visibility);
    }
    if (message.fileSystemPath !== "") {
      obj.fileSystemPath = message.fileSystemPath;
    }
    if (message.status !== 0) {
      obj.status = projectStatusToJSON(message.status);
    }
    if (message.templateId !== "") {
      obj.templateId = message.templateId;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.containerUrl !== undefined && message.containerUrl !== null) {
      obj.containerUrl = message.containerUrl;
    }
    if (message.createdAt !== "") {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== "") {
      obj.updatedAt = message.updatedAt;
    }
    return obj;
  },

  create(base?: DeepPartial<Project>): Project {
    return Project.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Project>): Project {
    const message = createBaseProject();
    message.id = object.id ?? "";
    message.slug = object.slug ?? "";
    message.description = object.description ?? undefined;
    message.visibility = object.visibility ?? 0;
    message.fileSystemPath = object.fileSystemPath ?? "";
    message.status = object.status ?? 0;
    message.templateId = object.templateId ?? "";
    message.userId = object.userId ?? "";
    message.containerUrl = object.containerUrl ?? undefined;
    message.createdAt = object.createdAt ?? "";
    message.updatedAt = object.updatedAt ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
