// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.4
// source: proto/template.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "template";

export enum Environment {
  ENVIRONMENT_UNSPECIFIED = 0,
  ENVIRONMENT_BROWSER = 1,
  ENVIRONMENT_SERVER = 2,
  UNRECOGNIZED = -1,
}

export function environmentFromJSON(object: any): Environment {
  switch (object) {
    case 0:
    case "ENVIRONMENT_UNSPECIFIED":
      return Environment.ENVIRONMENT_UNSPECIFIED;
    case 1:
    case "ENVIRONMENT_BROWSER":
      return Environment.ENVIRONMENT_BROWSER;
    case 2:
    case "ENVIRONMENT_SERVER":
      return Environment.ENVIRONMENT_SERVER;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Environment.UNRECOGNIZED;
  }
}

export function environmentToJSON(object: Environment): string {
  switch (object) {
    case Environment.ENVIRONMENT_UNSPECIFIED:
      return "ENVIRONMENT_UNSPECIFIED";
    case Environment.ENVIRONMENT_BROWSER:
      return "ENVIRONMENT_BROWSER";
    case Environment.ENVIRONMENT_SERVER:
      return "ENVIRONMENT_SERVER";
    case Environment.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface GetAllTemplatesRequest {
  language?: string | null | undefined;
  environment?: Environment | null | undefined;
}

export interface GetAllTemplatesResponse {
  templates: Template[];
}

export interface Template {
  id: string;
  slug: string;
  technologies: string[];
  language: string;
  environment: Environment;
  repoUrl: string;
  description?: string | null | undefined;
}

function createBaseGetAllTemplatesRequest(): GetAllTemplatesRequest {
  return { language: null, environment: null };
}

export const GetAllTemplatesRequest: MessageFns<GetAllTemplatesRequest> = {
  encode(message: GetAllTemplatesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.language !== undefined && message.language !== null) {
      writer.uint32(10).string(message.language);
    }
    if (message.environment !== undefined && message.environment !== null) {
      writer.uint32(16).int32(message.environment);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetAllTemplatesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAllTemplatesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.language = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.environment = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetAllTemplatesRequest {
    return {
      language: isSet(object.language) ? globalThis.String(object.language) : null,
      environment: isSet(object.environment) ? environmentFromJSON(object.environment) : null,
    };
  },

  toJSON(message: GetAllTemplatesRequest): unknown {
    const obj: any = {};
    if (message.language !== undefined && message.language !== null) {
      obj.language = message.language;
    }
    if (message.environment !== undefined && message.environment !== null) {
      obj.environment = environmentToJSON(message.environment);
    }
    return obj;
  },

  create(base?: DeepPartial<GetAllTemplatesRequest>): GetAllTemplatesRequest {
    return GetAllTemplatesRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetAllTemplatesRequest>): GetAllTemplatesRequest {
    const message = createBaseGetAllTemplatesRequest();
    message.language = object.language ?? undefined;
    message.environment = object.environment ?? undefined;
    return message;
  },
};

function createBaseGetAllTemplatesResponse(): GetAllTemplatesResponse {
  return { templates: [] };
}

export const GetAllTemplatesResponse: MessageFns<GetAllTemplatesResponse> = {
  encode(message: GetAllTemplatesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.templates) {
      Template.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetAllTemplatesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAllTemplatesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.templates.push(Template.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetAllTemplatesResponse {
    return {
      templates: globalThis.Array.isArray(object?.templates)
        ? object.templates.map((e: any) => Template.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GetAllTemplatesResponse): unknown {
    const obj: any = {};
    if (message.templates?.length) {
      obj.templates = message.templates.map((e) => Template.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<GetAllTemplatesResponse>): GetAllTemplatesResponse {
    return GetAllTemplatesResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetAllTemplatesResponse>): GetAllTemplatesResponse {
    const message = createBaseGetAllTemplatesResponse();
    message.templates = object.templates?.map((e) => Template.fromPartial(e)) || [];
    return message;
  },
};

function createBaseTemplate(): Template {
  return { id: "", slug: "", technologies: [], language: "", environment: 0, repoUrl: "", description: null };
}

export const Template: MessageFns<Template> = {
  encode(message: Template, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.slug !== "") {
      writer.uint32(18).string(message.slug);
    }
    for (const v of message.technologies) {
      writer.uint32(26).string(v!);
    }
    if (message.language !== "") {
      writer.uint32(34).string(message.language);
    }
    if (message.environment !== 0) {
      writer.uint32(40).int32(message.environment);
    }
    if (message.repoUrl !== "") {
      writer.uint32(58).string(message.repoUrl);
    }
    if (message.description !== undefined && message.description !== null) {
      writer.uint32(66).string(message.description);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Template {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTemplate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.slug = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.technologies.push(reader.string());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.language = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.environment = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.repoUrl = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.description = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Template {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      slug: isSet(object.slug) ? globalThis.String(object.slug) : "",
      technologies: globalThis.Array.isArray(object?.technologies)
        ? object.technologies.map((e: any) => globalThis.String(e))
        : [],
      language: isSet(object.language) ? globalThis.String(object.language) : "",
      environment: isSet(object.environment) ? environmentFromJSON(object.environment) : 0,
      repoUrl: isSet(object.repoUrl)
        ? globalThis.String(object.repoUrl)
        : isSet(object.repo_url)
        ? globalThis.String(object.repo_url)
        : "",
      description: isSet(object.description) ? globalThis.String(object.description) : null,
    };
  },

  toJSON(message: Template): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.slug !== "") {
      obj.slug = message.slug;
    }
    if (message.technologies?.length) {
      obj.technologies = message.technologies;
    }
    if (message.language !== "") {
      obj.language = message.language;
    }
    if (message.environment !== 0) {
      obj.environment = environmentToJSON(message.environment);
    }
    if (message.repoUrl !== "") {
      obj.repoUrl = message.repoUrl;
    }
    if (message.description !== undefined && message.description !== null) {
      obj.description = message.description;
    }
    return obj;
  },

  create(base?: DeepPartial<Template>): Template {
    return Template.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Template>): Template {
    const message = createBaseTemplate();
    message.id = object.id ?? "";
    message.slug = object.slug ?? "";
    message.technologies = object.technologies?.map((e) => e) || [];
    message.language = object.language ?? "";
    message.environment = object.environment ?? 0;
    message.repoUrl = object.repoUrl ?? "";
    message.description = object.description ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
