// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.4
// source: proto/auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "auth";

export enum OAuthProvider {
  O_AUTH_PROVIDER_UNSPECIFIED = 0,
  O_AUTH_PROVIDER_GOOGLE = 1,
  O_AUTH_PROVIDER_GITHUB = 2,
  UNRECOGNIZED = -1,
}

export interface LoginWithEmailRequest {
  email: string;
}

export interface LoginWithEmailResponse {
  message: string;
}

export interface VerifyOtpRequest {
  email: string;
  otp: string;
}

export interface VerifyOtpResponse {
  accessToken: string;
  refreshToken: string;
}

export interface LoginWithOAuthRequest {
  email: string;
  name: string;
  profilePicture: string;
  accountId: string;
  provider: OAuthProvider;
}

export interface LoginWithOAuthResponse {
  accessToken: string;
  refreshToken: string;
}

export interface VerifyRefreshTokenRequest {
  oldRefreshToken: string;
  id: string;
}

export interface VerifyRefreshTokenResponse {
  id: string;
  email: string;
}

export interface RefreshTokenRequest {
  id: string;
  email: string;
}

export interface RefreshTokenResponse {
  accessToken: string;
  refreshToken: string;
}

export interface LogoutRequest {
  id: string;
}

export interface LogoutResponse {
  message: string;
}

export const AUTH_PACKAGE_NAME = "auth";

export interface AuthServiceClient {
  loginWithEmail(request: LoginWithEmailRequest): Observable<LoginWithEmailResponse>;

  verifyOtp(request: VerifyOtpRequest): Observable<VerifyOtpResponse>;

  loginWithOAuth(request: LoginWithOAuthRequest): Observable<LoginWithOAuthResponse>;

  verifyRefreshToken(request: VerifyRefreshTokenRequest): Observable<VerifyRefreshTokenResponse>;

  refreshToken(request: RefreshTokenRequest): Observable<RefreshTokenResponse>;

  logout(request: LogoutRequest): Observable<LogoutResponse>;
}

export interface AuthServiceController {
  loginWithEmail(
    request: LoginWithEmailRequest,
  ): Promise<LoginWithEmailResponse> | Observable<LoginWithEmailResponse> | LoginWithEmailResponse;

  verifyOtp(request: VerifyOtpRequest): Promise<VerifyOtpResponse> | Observable<VerifyOtpResponse> | VerifyOtpResponse;

  loginWithOAuth(
    request: LoginWithOAuthRequest,
  ): Promise<LoginWithOAuthResponse> | Observable<LoginWithOAuthResponse> | LoginWithOAuthResponse;

  verifyRefreshToken(
    request: VerifyRefreshTokenRequest,
  ): Promise<VerifyRefreshTokenResponse> | Observable<VerifyRefreshTokenResponse> | VerifyRefreshTokenResponse;

  refreshToken(
    request: RefreshTokenRequest,
  ): Promise<RefreshTokenResponse> | Observable<RefreshTokenResponse> | RefreshTokenResponse;

  logout(request: LogoutRequest): Promise<LogoutResponse> | Observable<LogoutResponse> | LogoutResponse;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "loginWithEmail",
      "verifyOtp",
      "loginWithOAuth",
      "verifyRefreshToken",
      "refreshToken",
      "logout",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
