// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.4
// source: proto/project.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "project";

export enum ProjectVisibility {
  PROJECT_VISIBILITY_UNSPECIFIED = 0,
  PROJECT_VISIBILITY_PUBLIC = 1,
  PROJECT_VISIBILITY_PRIVATE = 2,
  UNRECOGNIZED = -1,
}

export enum ProjectStatus {
  PROJECT_STATUS_UNSPECIFIED = 0,
  PROJECT_STATUS_BOOTING = 1,
  PROJECT_STATUS_LOADING_FILES = 2,
  PROJECT_STATUS_INSTALLING_DEPENDENCIES = 3,
  PROJECT_STATUS_READY = 4,
  PROJECT_STATUS_ERROR = 5,
  PROJECT_STATUS_STOPPED = 6,
  UNRECOGNIZED = -1,
}

export interface CreateProjectRequest {
  slug: string;
  userId: string;
  templateId: string;
  description?: string | null | undefined;
  visibility: ProjectVisibility;
}

export interface CreateProjectResponse {
  project: Project | null;
}

export interface GetProjectRequest {
  slug: string;
  userId: string;
}

export interface GetProjectResponse {
  project: Project | null;
}

export interface EditProjectRequest {
  slug: string;
  userId: string;
  description?: string | null | undefined;
  visibility?: ProjectVisibility | null | undefined;
  templateId?: string | null | undefined;
  fileSystemPath?: string | null | undefined;
  status?: ProjectStatus | null | undefined;
}

export interface EditProjectResponse {
  project: Project | null;
}

export interface Project {
  id: string;
  slug: string;
  description?: string | null | undefined;
  visibility: ProjectVisibility;
  fileSystemPath: string;
  status: ProjectStatus;
  templateId: string;
  userId: string;
  createdAt: string;
  updatedAt: string;
}

export const PROJECT_PACKAGE_NAME = "project";

export interface ProjectServiceClient {
  createProject(request: CreateProjectRequest): Observable<CreateProjectResponse>;

  getProject(request: GetProjectRequest): Observable<GetProjectResponse>;

  editProject(request: EditProjectRequest): Observable<EditProjectResponse>;
}

export interface ProjectServiceController {
  createProject(
    request: CreateProjectRequest,
  ): Promise<CreateProjectResponse> | Observable<CreateProjectResponse> | CreateProjectResponse;

  getProject(
    request: GetProjectRequest,
  ): Promise<GetProjectResponse> | Observable<GetProjectResponse> | GetProjectResponse;

  editProject(
    request: EditProjectRequest,
  ): Promise<EditProjectResponse> | Observable<EditProjectResponse> | EditProjectResponse;
}

export function ProjectServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createProject", "getProject", "editProject"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ProjectService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ProjectService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PROJECT_SERVICE_NAME = "ProjectService";
