// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.4
// source: proto/template.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "template";

export enum Environment {
  ENVIRONMENT_UNSPECIFIED = 0,
  ENVIRONMENT_BROWSER = 1,
  ENVIRONMENT_SERVER = 2,
  UNRECOGNIZED = -1,
}

export interface GetAllTemplatesRequest {
  language?: string | null | undefined;
  environment?: Environment | null | undefined;
}

export interface GetAllTemplatesResponse {
  templates: Template[];
}

export interface Template {
  id: string;
  slug: string;
  technologies: string[];
  language: string;
  environment: Environment;
  folderUrl: string;
  description?: string | null | undefined;
}

export const TEMPLATE_PACKAGE_NAME = "template";

export interface TemplateServiceClient {
  getAllTemplates(request: GetAllTemplatesRequest): Observable<GetAllTemplatesResponse>;
}

export interface TemplateServiceController {
  getAllTemplates(
    request: GetAllTemplatesRequest,
  ): Promise<GetAllTemplatesResponse> | Observable<GetAllTemplatesResponse> | GetAllTemplatesResponse;
}

export function TemplateServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getAllTemplates"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("TemplateService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("TemplateService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const TEMPLATE_SERVICE_NAME = "TemplateService";
