// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.4
// source: proto/user.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "user";

export interface CreateUserIfNotExistsRequest {
  email: string;
  name?: string | null | undefined;
  image?: string | null | undefined;
}

export interface CreateUserIfNotExistsResponse {
  user: User | null;
}

export interface GetUserRequest {
  id: string;
}

export interface GetUserResponse {
  user: User | null;
}

export interface UpdateUserRequest {
  id: string;
  name?: string | null | undefined;
  image?: string | null | undefined;
}

export interface UpdateUserResponse {
  user: User | null;
}

export interface User {
  id: string;
  email: string;
  name?: string | null | undefined;
  image?: string | null | undefined;
}

export const USER_PACKAGE_NAME = "user";

export interface UserServiceClient {
  createUserIfNotExists(request: CreateUserIfNotExistsRequest): Observable<CreateUserIfNotExistsResponse>;

  getUser(request: GetUserRequest): Observable<GetUserResponse>;

  updateUser(request: UpdateUserRequest): Observable<UpdateUserResponse>;
}

export interface UserServiceController {
  createUserIfNotExists(
    request: CreateUserIfNotExistsRequest,
  ): Promise<CreateUserIfNotExistsResponse> | Observable<CreateUserIfNotExistsResponse> | CreateUserIfNotExistsResponse;

  getUser(request: GetUserRequest): Promise<GetUserResponse> | Observable<GetUserResponse> | GetUserResponse;

  updateUser(
    request: UpdateUserRequest,
  ): Promise<UpdateUserResponse> | Observable<UpdateUserResponse> | UpdateUserResponse;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createUserIfNotExists", "getUser", "updateUser"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
